sudo: false # Stop any possible warning from Travis CI

# OS-agnostic, no action required

language: node_js
node_js:
  - v6 # Latest known Stable
  - v4 # LTS
  # No support for old 0.* versions (at the time of writing we should support them
  # but at the time of publishing they will almost certainly be discontinued - mid-2017)

# Native module support (serialport may need it)
# We need a C++11 compiler
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# Prepare for code coverage generation and reporting
before_install: npm install codecov nyc

# Now do it!
script:
  - npm run coverage # Generate coverage report and test things
  - nyc report --reporter=text-lcov | codecov # Publish coverage data
