window.esdocSearchIndex = [
  [
    "@cansat-icarus/capture-lib/src/icarus/backend/index.js~backend",
    "class/src/icarus/backend/index.js~Backend.html",
    "<span>Backend</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/backend/index.js</span>",
    "class"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/classifier/index.js~classifier",
    "class/src/icarus/classifier/index.js~Classifier.html",
    "<span>Classifier</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/classifier/index.js</span>",
    "class"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js~ds18b20",
    "function/index.html#static-function-DS18B20",
    "<span>DS18B20</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/lib/backoff-wrapper.js~exponentialbackoff",
    "class/src/lib/backoff-wrapper.js~ExponentialBackoff.html",
    "<span>ExponentialBackoff</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/lib/backoff-wrapper.js</span>",
    "class"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/parser.js~icarusparser",
    "class/src/icarus/data-handler/parser.js~IcarusParser.html",
    "<span>IcarusParser</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/parser.js</span>",
    "class"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js~lis331hh_24g",
    "function/index.html#static-function-LIS331HH_24G",
    "<span>LIS331HH_24G</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js~mma7361_6g",
    "function/index.html#static-function-MMA7361_6G",
    "<span>MMA7361_6G</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js~mpx4115a",
    "function/index.html#static-function-MPX4115A",
    "<span>MPX4115A</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/parser.js~parser",
    "class/src/parser.js~Parser.html",
    "<span>Parser</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/parser.js</span>",
    "class"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/backend/replicator.js~replicator",
    "class/src/icarus/backend/replicator.js~Replicator.html",
    "<span>Replicator</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/backend/replicator.js</span>",
    "class"
  ],
  [
    "@cansat-icarus/capture-lib/src/serial.js~serial",
    "class/src/serial.js~Serial.html",
    "<span>Serial</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/serial.js</span>",
    "class"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/station.js~station",
    "class/src/icarus/station.js~Station.html",
    "<span>Station</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/station.js</span>",
    "class"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js~analogtomv",
    "function/index.html#static-function-analogToMV",
    "<span>analogToMV</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/lib/log.js~createlogger",
    "function/index.html#static-function-createLogger",
    "<span>createLogger</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/lib/log.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/index.js~datahandler",
    "function/index.html#static-function-dataHandler",
    "<span>dataHandler</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/index.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js~getbit",
    "function/index.html#static-function-getBit",
    "<span>getBit</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/lib/db.js~getdb",
    "function/index.html#static-function-getDB",
    "<span>getDB</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/lib/db.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/lib/db.js~getremotedb",
    "function/index.html#static-function-getRemoteDB",
    "<span>getRemoteDB</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/lib/db.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js~gpsaltitude",
    "function/index.html#static-function-gpsAltitude",
    "<span>gpsAltitude</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js~gpscoordinate",
    "function/index.html#static-function-gpsCoordinate",
    "<span>gpsCoordinate</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js~gpscourse",
    "function/index.html#static-function-gpsCourse",
    "<span>gpsCourse</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js~gpsflags",
    "function/index.html#static-function-gpsFlags",
    "<span>gpsFlags</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js~gpsspeed",
    "function/index.html#static-function-gpsSpeed",
    "<span>gpsSpeed</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/unit-conv.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/serial.js~listports",
    "function/index.html#static-function-listPorts",
    "<span>listPorts</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/serial.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/cansat-strings.js~messages",
    "variable/index.html#static-variable-messages",
    "<span>messages</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/cansat-strings.js</span>",
    "variable"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/classifier/packet-heuristics.js~minmaxh",
    "function/index.html#static-function-minmaxH",
    "<span>minmaxH</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/classifier/packet-heuristics.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/cansat-strings.js~modulenames",
    "variable/index.html#static-variable-moduleNames",
    "<span>moduleNames</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/cansat-strings.js</span>",
    "variable"
  ],
  [
    "@cansat-icarus/capture-lib/src/lib/path.js~normalizepath",
    "function/index.html#static-function-normalizePath",
    "<span>normalizePath</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/lib/path.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/index.js~parser",
    "function/index.html#static-function-parser",
    "<span>parser</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/index.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/lib/pass-event.js~passevent",
    "function/index.html#static-function-passEvent",
    "<span>passEvent</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/lib/pass-event.js</span>",
    "function"
  ],
  [
    "@cansat-icarus/capture-lib/src/lib/path.js~pathprefix",
    "variable/index.html#static-variable-pathPrefix",
    "<span>pathPrefix</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/lib/path.js</span>",
    "variable"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/station.js~tminuspid",
    "variable/index.html#static-variable-tMinusPid",
    "<span>tMinusPid</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/station.js</span>",
    "variable"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/station.js~tminusvid",
    "variable/index.html#static-variable-tMinusVid",
    "<span>tMinusVid</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/station.js</span>",
    "variable"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/data-handler/index.js~tmbuffer",
    "variable/index.html#static-variable-tmBuffer",
    "<span>tmBuffer</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/data-handler/index.js</span>",
    "variable"
  ],
  [
    "@cansat-icarus/capture-lib/src/icarus/classifier/packet-heuristics.js~variationh",
    "function/index.html#static-function-variationH",
    "<span>variationH</span> <span class=\"search-result-import-path\">@cansat-icarus/capture-lib/src/icarus/classifier/packet-heuristics.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/icarus/backend/index.js",
    "file/src/icarus/backend/index.js.html",
    "src/icarus/backend/index.js",
    "file"
  ],
  [
    "src/icarus/backend/index.js~backend#_log",
    "class/src/icarus/backend/index.js~Backend.html#instance-member-_log",
    "src/icarus/backend/index.js~Backend#_log",
    "member"
  ],
  [
    "src/icarus/backend/index.js~backend#_socket",
    "class/src/icarus/backend/index.js~Backend.html#instance-member-_socket",
    "src/icarus/backend/index.js~Backend#_socket",
    "member"
  ],
  [
    "src/icarus/backend/index.js~backend#_state",
    "class/src/icarus/backend/index.js~Backend.html#instance-member-_state",
    "src/icarus/backend/index.js~Backend#_state",
    "member"
  ],
  [
    "src/icarus/backend/index.js~backend#_updatestate",
    "class/src/icarus/backend/index.js~Backend.html#instance-method-_updateState",
    "src/icarus/backend/index.js~Backend#_updateState",
    "method"
  ],
  [
    "src/icarus/backend/index.js~backend#cleanup",
    "class/src/icarus/backend/index.js~Backend.html#instance-method-cleanup",
    "src/icarus/backend/index.js~Backend#cleanup",
    "method"
  ],
  [
    "src/icarus/backend/index.js~backend#connect",
    "class/src/icarus/backend/index.js~Backend.html#instance-method-connect",
    "src/icarus/backend/index.js~Backend#connect",
    "method"
  ],
  [
    "src/icarus/backend/index.js~backend#constructor",
    "class/src/icarus/backend/index.js~Backend.html#instance-constructor-constructor",
    "src/icarus/backend/index.js~Backend#constructor",
    "method"
  ],
  [
    "src/icarus/backend/index.js~backend#datareplicator",
    "class/src/icarus/backend/index.js~Backend.html#instance-member-dataReplicator",
    "src/icarus/backend/index.js~Backend#dataReplicator",
    "member"
  ],
  [
    "src/icarus/backend/index.js~backend#disconnect",
    "class/src/icarus/backend/index.js~Backend.html#instance-method-disconnect",
    "src/icarus/backend/index.js~Backend#disconnect",
    "method"
  ],
  [
    "src/icarus/backend/index.js~backend#logreplicator",
    "class/src/icarus/backend/index.js~Backend.html#instance-member-logReplicator",
    "src/icarus/backend/index.js~Backend#logReplicator",
    "member"
  ],
  [
    "src/icarus/backend/index.js~backend#name",
    "class/src/icarus/backend/index.js~Backend.html#instance-member-name",
    "src/icarus/backend/index.js~Backend#name",
    "member"
  ],
  [
    "src/icarus/backend/replicator.js",
    "file/src/icarus/backend/replicator.js.html",
    "src/icarus/backend/replicator.js",
    "file"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#_backoff",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-member-_backoff",
    "src/icarus/backend/replicator.js~Replicator#_backoff",
    "member"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#_cancelcurrentreplicator",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-method-_cancelCurrentReplicator",
    "src/icarus/backend/replicator.js~Replicator#_cancelCurrentReplicator",
    "method"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#_createreplicator",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-method-_createReplicator",
    "src/icarus/backend/replicator.js~Replicator#_createReplicator",
    "method"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#_ensurereplication",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-method-_ensureReplication",
    "src/icarus/backend/replicator.js~Replicator#_ensureReplication",
    "method"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#_log",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-member-_log",
    "src/icarus/backend/replicator.js~Replicator#_log",
    "member"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#_replication",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-member-_replication",
    "src/icarus/backend/replicator.js~Replicator#_replication",
    "member"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#_sourcedb",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-member-_sourceDB",
    "src/icarus/backend/replicator.js~Replicator#_sourceDB",
    "member"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#_state",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-member-_state",
    "src/icarus/backend/replicator.js~Replicator#_state",
    "member"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#_targetdb",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-member-_targetDB",
    "src/icarus/backend/replicator.js~Replicator#_targetDB",
    "member"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#_updatestate",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-method-_updateState",
    "src/icarus/backend/replicator.js~Replicator#_updateState",
    "method"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#cleanup",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-method-cleanup",
    "src/icarus/backend/replicator.js~Replicator#cleanup",
    "method"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#constructor",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-constructor-constructor",
    "src/icarus/backend/replicator.js~Replicator#constructor",
    "method"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#replicate",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-method-replicate",
    "src/icarus/backend/replicator.js~Replicator#replicate",
    "method"
  ],
  [
    "src/icarus/backend/replicator.js~replicator#stop",
    "class/src/icarus/backend/replicator.js~Replicator.html#instance-method-stop",
    "src/icarus/backend/replicator.js~Replicator#stop",
    "method"
  ],
  [
    "src/icarus/classifier/index.js",
    "file/src/icarus/classifier/index.js.html",
    "src/icarus/classifier/index.js",
    "file"
  ],
  [
    "src/icarus/classifier/index.js~classifier#_lastdata",
    "class/src/icarus/classifier/index.js~Classifier.html#instance-member-_lastData",
    "src/icarus/classifier/index.js~Classifier#_lastData",
    "member"
  ],
  [
    "src/icarus/classifier/index.js~classifier#_log",
    "class/src/icarus/classifier/index.js~Classifier.html#instance-member-_log",
    "src/icarus/classifier/index.js~Classifier#_log",
    "member"
  ],
  [
    "src/icarus/classifier/index.js~classifier#classifypacket",
    "class/src/icarus/classifier/index.js~Classifier.html#instance-method-classifyPacket",
    "src/icarus/classifier/index.js~Classifier#classifyPacket",
    "method"
  ],
  [
    "src/icarus/classifier/index.js~classifier#classifystationinc",
    "class/src/icarus/classifier/index.js~Classifier.html#instance-method-classifyStationInc",
    "src/icarus/classifier/index.js~Classifier#classifyStationInc",
    "method"
  ],
  [
    "src/icarus/classifier/index.js~classifier#constructor",
    "class/src/icarus/classifier/index.js~Classifier.html#instance-constructor-constructor",
    "src/icarus/classifier/index.js~Classifier#constructor",
    "method"
  ],
  [
    "src/icarus/classifier/index.js~classifier#stationscore",
    "class/src/icarus/classifier/index.js~Classifier.html#instance-member-stationScore",
    "src/icarus/classifier/index.js~Classifier#stationScore",
    "member"
  ],
  [
    "src/icarus/classifier/packet-heuristics.js",
    "file/src/icarus/classifier/packet-heuristics.js.html",
    "src/icarus/classifier/packet-heuristics.js",
    "file"
  ],
  [
    "src/icarus/data-handler/cansat-strings.js",
    "file/src/icarus/data-handler/cansat-strings.js.html",
    "src/icarus/data-handler/cansat-strings.js",
    "file"
  ],
  [
    "src/icarus/data-handler/index.js",
    "file/src/icarus/data-handler/index.js.html",
    "src/icarus/data-handler/index.js",
    "file"
  ],
  [
    "src/icarus/data-handler/parser.js",
    "file/src/icarus/data-handler/parser.js.html",
    "src/icarus/data-handler/parser.js",
    "file"
  ],
  [
    "src/icarus/data-handler/parser.js~icarusparser#_raw",
    "class/src/icarus/data-handler/parser.js~IcarusParser.html#instance-member-_raw",
    "src/icarus/data-handler/parser.js~IcarusParser#_raw",
    "member"
  ],
  [
    "src/icarus/data-handler/parser.js~icarusparser#parse",
    "class/src/icarus/data-handler/parser.js~IcarusParser.html#instance-method-parse",
    "src/icarus/data-handler/parser.js~IcarusParser#parse",
    "method"
  ],
  [
    "src/icarus/data-handler/unit-conv.js",
    "file/src/icarus/data-handler/unit-conv.js.html",
    "src/icarus/data-handler/unit-conv.js",
    "file"
  ],
  [
    "src/icarus/station.js",
    "file/src/icarus/station.js.html",
    "src/icarus/station.js",
    "file"
  ],
  [
    "src/icarus/station.js~station#_log",
    "class/src/icarus/station.js~Station.html#instance-member-_log",
    "src/icarus/station.js~Station#_log",
    "member"
  ],
  [
    "src/icarus/station.js~station#backend",
    "class/src/icarus/station.js~Station.html#instance-member-backend",
    "src/icarus/station.js~Station#backend",
    "member"
  ],
  [
    "src/icarus/station.js~station#classifier",
    "class/src/icarus/station.js~Station.html#instance-member-classifier",
    "src/icarus/station.js~Station#classifier",
    "member"
  ],
  [
    "src/icarus/station.js~station#cleanup",
    "class/src/icarus/station.js~Station.html#instance-method-cleanup",
    "src/icarus/station.js~Station#cleanup",
    "method"
  ],
  [
    "src/icarus/station.js~station#constructor",
    "class/src/icarus/station.js~Station.html#instance-constructor-constructor",
    "src/icarus/station.js~Station#constructor",
    "method"
  ],
  [
    "src/icarus/station.js~station#db",
    "class/src/icarus/station.js~Station.html#instance-member-db",
    "src/icarus/station.js~Station#db",
    "member"
  ],
  [
    "src/icarus/station.js~station#getavailableports",
    "class/src/icarus/station.js~Station.html#instance-method-getAvailablePorts",
    "src/icarus/station.js~Station#getAvailablePorts",
    "method"
  ],
  [
    "src/icarus/station.js~station#logdb",
    "class/src/icarus/station.js~Station.html#instance-member-logDB",
    "src/icarus/station.js~Station#logDB",
    "member"
  ],
  [
    "src/icarus/station.js~station#name",
    "class/src/icarus/station.js~Station.html#instance-member-name",
    "src/icarus/station.js~Station#name",
    "member"
  ],
  [
    "src/icarus/station.js~station#serial",
    "class/src/icarus/station.js~Station.html#instance-member-serial",
    "src/icarus/station.js~Station#serial",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/lib/backoff-wrapper.js",
    "file/src/lib/backoff-wrapper.js.html",
    "src/lib/backoff-wrapper.js",
    "file"
  ],
  [
    "src/lib/backoff-wrapper.js~exponentialbackoff#_backoffnumber",
    "class/src/lib/backoff-wrapper.js~ExponentialBackoff.html#instance-member-_backoffNumber",
    "src/lib/backoff-wrapper.js~ExponentialBackoff#_backoffNumber",
    "member"
  ],
  [
    "src/lib/backoff-wrapper.js~exponentialbackoff#_strategy",
    "class/src/lib/backoff-wrapper.js~ExponentialBackoff.html#instance-member-_strategy",
    "src/lib/backoff-wrapper.js~ExponentialBackoff#_strategy",
    "member"
  ],
  [
    "src/lib/backoff-wrapper.js~exponentialbackoff#_timeoutid",
    "class/src/lib/backoff-wrapper.js~ExponentialBackoff.html#instance-member-_timeoutID",
    "src/lib/backoff-wrapper.js~ExponentialBackoff#_timeoutID",
    "member"
  ],
  [
    "src/lib/backoff-wrapper.js~exponentialbackoff#backoff",
    "class/src/lib/backoff-wrapper.js~ExponentialBackoff.html#instance-method-backoff",
    "src/lib/backoff-wrapper.js~ExponentialBackoff#backoff",
    "method"
  ],
  [
    "src/lib/backoff-wrapper.js~exponentialbackoff#constructor",
    "class/src/lib/backoff-wrapper.js~ExponentialBackoff.html#instance-constructor-constructor",
    "src/lib/backoff-wrapper.js~ExponentialBackoff#constructor",
    "method"
  ],
  [
    "src/lib/backoff-wrapper.js~exponentialbackoff#reset",
    "class/src/lib/backoff-wrapper.js~ExponentialBackoff.html#instance-method-reset",
    "src/lib/backoff-wrapper.js~ExponentialBackoff#reset",
    "method"
  ],
  [
    "src/lib/backoff-wrapper.js~exponentialbackoff#success",
    "class/src/lib/backoff-wrapper.js~ExponentialBackoff.html#instance-method-success",
    "src/lib/backoff-wrapper.js~ExponentialBackoff#success",
    "method"
  ],
  [
    "src/lib/db.js",
    "file/src/lib/db.js.html",
    "src/lib/db.js",
    "file"
  ],
  [
    "src/lib/log.js",
    "file/src/lib/log.js.html",
    "src/lib/log.js",
    "file"
  ],
  [
    "src/lib/pass-event.js",
    "file/src/lib/pass-event.js.html",
    "src/lib/pass-event.js",
    "file"
  ],
  [
    "src/lib/path.js",
    "file/src/lib/path.js.html",
    "src/lib/path.js",
    "file"
  ],
  [
    "src/parser.js",
    "file/src/parser.js.html",
    "src/parser.js",
    "file"
  ],
  [
    "src/parser.js~parser#_i",
    "class/src/parser.js~Parser.html#instance-member-_i",
    "src/parser.js~Parser#_i",
    "member"
  ],
  [
    "src/parser.js~parser#_raw",
    "class/src/parser.js~Parser.html#instance-member-_raw",
    "src/parser.js~Parser#_raw",
    "member"
  ],
  [
    "src/parser.js~parser#constructor",
    "class/src/parser.js~Parser.html#instance-constructor-constructor",
    "src/parser.js~Parser#constructor",
    "method"
  ],
  [
    "src/parser.js~parser#endianess",
    "class/src/parser.js~Parser.html#instance-member-endianess",
    "src/parser.js~Parser#endianess",
    "member"
  ],
  [
    "src/parser.js~parser#packet",
    "class/src/parser.js~Parser.html#instance-member-packet",
    "src/parser.js~Parser#packet",
    "member"
  ],
  [
    "src/parser.js~parser#parse",
    "class/src/parser.js~Parser.html#instance-method-parse",
    "src/parser.js~Parser#parse",
    "method"
  ],
  [
    "src/parser.js~parser#readboolean",
    "class/src/parser.js~Parser.html#instance-method-readBoolean",
    "src/parser.js~Parser#readBoolean",
    "method"
  ],
  [
    "src/parser.js~parser#readchar",
    "class/src/parser.js~Parser.html#instance-method-readChar",
    "src/parser.js~Parser#readChar",
    "method"
  ],
  [
    "src/parser.js~parser#readfloat",
    "class/src/parser.js~Parser.html#instance-method-readFloat",
    "src/parser.js~Parser#readFloat",
    "method"
  ],
  [
    "src/parser.js~parser#readint",
    "class/src/parser.js~Parser.html#instance-method-readInt",
    "src/parser.js~Parser#readInt",
    "method"
  ],
  [
    "src/parser.js~parser#readuint",
    "class/src/parser.js~Parser.html#instance-method-readUInt",
    "src/parser.js~Parser#readUInt",
    "method"
  ],
  [
    "src/parser.js~parser#setvalue",
    "class/src/parser.js~Parser.html#instance-method-setValue",
    "src/parser.js~Parser#setValue",
    "method"
  ],
  [
    "src/serial.js",
    "file/src/serial.js.html",
    "src/serial.js",
    "file"
  ],
  [
    "src/serial.js~serial#_baud",
    "class/src/serial.js~Serial.html#instance-member-_baud",
    "src/serial.js~Serial#_baud",
    "member"
  ],
  [
    "src/serial.js~serial#_createport",
    "class/src/serial.js~Serial.html#instance-method-_createPort",
    "src/serial.js~Serial#_createPort",
    "method"
  ],
  [
    "src/serial.js~serial#_destroyport",
    "class/src/serial.js~Serial.html#instance-method-_destroyPort",
    "src/serial.js~Serial#_destroyPort",
    "method"
  ],
  [
    "src/serial.js~serial#_log",
    "class/src/serial.js~Serial.html#instance-member-_log",
    "src/serial.js~Serial#_log",
    "member"
  ],
  [
    "src/serial.js~serial#_parser",
    "class/src/serial.js~Serial.html#instance-member-_parser",
    "src/serial.js~Serial#_parser",
    "member"
  ],
  [
    "src/serial.js~serial#_path",
    "class/src/serial.js~Serial.html#instance-member-_path",
    "src/serial.js~Serial#_path",
    "member"
  ],
  [
    "src/serial.js~serial#_port",
    "class/src/serial.js~Serial.html#instance-member-_port",
    "src/serial.js~Serial#_port",
    "member"
  ],
  [
    "src/serial.js~serial#_state",
    "class/src/serial.js~Serial.html#instance-member-_state",
    "src/serial.js~Serial#_state",
    "member"
  ],
  [
    "src/serial.js~serial#_updatestate",
    "class/src/serial.js~Serial.html#instance-method-_updateState",
    "src/serial.js~Serial#_updateState",
    "method"
  ],
  [
    "src/serial.js~serial#close",
    "class/src/serial.js~Serial.html#instance-method-close",
    "src/serial.js~Serial#close",
    "method"
  ],
  [
    "src/serial.js~serial#constructor",
    "class/src/serial.js~Serial.html#instance-constructor-constructor",
    "src/serial.js~Serial#constructor",
    "method"
  ],
  [
    "src/serial.js~serial#open",
    "class/src/serial.js~Serial.html#instance-method-open",
    "src/serial.js~Serial#open",
    "method"
  ],
  [
    "src/serial.js~serial#setpath",
    "class/src/serial.js~Serial.html#instance-method-setPath",
    "src/serial.js~Serial#setPath",
    "method"
  ]
]